name: Close inactive issues
on:
  workflow_dispatch

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-close: 14
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
